---
title: "001-taxon-name-alignment"
author: "jt-miller"
date: "2024-03-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Load Dependencies 
```{r}
library(data.table)
library(tidyverse)
library(rgnparser)
```
### Load Data
```{r}
raw_bocp_names <- fread("/home/jt-miller/Gurlab/BoCP/data/raw/USACANMEX_plantNamesFieldsAdded.csv",encoding = "UTF-8")
wfo_backbone <- fread("/home/jt-miller/Soltis-lab/taxonomic-harmonization-resources/taxonomic-backbones/WFO_Backbone/classification.csv")
```
### Prepare Data
Currently the .csv file broke authorship into several fields where there are ',' present (as this is a comma seperated file). Here, I'll concatenate these fields together so we can parse out the whole later
```{r}
# Collapse fields into one by adding a space when there is a string present
raw_bocp_names$concatenatedName <- apply(raw_bocp_names[, c("Name", "ExteriorNameAuthorship", "ExteriorNameAuthorship2", "V5")], 1, function(x) paste(x[x != ""], collapse = ", "))
# Select only fields of interest 
bocp_names <- raw_bocp_names[, .(TropicosNameID = NameID, concatenatedName)]
```

Parsing the data, we need separate columns for the species name and the authorship.
```{r}
bocp_parsed_names <- gn_parse_tidy(bocp_names$concatenatedName)  # break up names

bocp_parsed_names_df <- merge(bocp_names, bocp_parsed_names, by.x = 'concatenatedName', by.y = 'verbatim')
```

```{r}

```



